### ISSUE TITLE
the repository settings anchor/link in readme.md does not work

### ISSUE THREAD

**Issue by poanchen** [Fizzyo/fizzyo.github.io#1]
It seems like the link (https://github.com/Fizzyo/fizzyo.github.io/settings) will only work for people who has permission to the repository. Probably only the admin and owner has access to it according to https://help.github.com/articles/repository-permission-levels-for-an-organization/ unless you explicitly set it.  And, that is probably something you might not want to do and It seems like the readme is just giving the user idea of what the url might looks like. Instead of giving a straight link that might not work for user (404 page), I would probably do something like this,

`
https://github.com/your-username/your-repo-name/settings
`
so that user would know what to do

Thank you for reading! =)

**Comment by leestott** [comment]
updated setting page to include url link
